spring:
  r2dbc:
    password: 123456
    username: root
    url: r2dbc:mysql://localhost:3306/test
    name: test

  main:
    allow-circular-references: true
#  security:
#    user:
#      name: admin
#      password: 123456


logging:
  level:
    org.springframework.r2dbc: debug

